export const POST_TABLE_LISTING= "POST_TABLE_LISTING";
export const POST_TABLE_DET= "POST_TABLE_DET";
export const POST_EDIT_DET= "POST_EDIT_DET";
export const POST_ALL_SIC_TABLE= "POST_ALL_SIC_TABLE";
export const POST_SICBO_BET_TRANS= "POST_SICBO_BET_TRANS";
export const POST_SIC_PAY_RATE= "POST_SIC_PAY_RATE";
export const POST_SIC_TRANS_DETAIL= "POST_SIC_TRANS_DETAIL";
