export const GET_WALLET_TYPE_LIST= "GET_WALLET_TYPE_LIST";
export const GET_WALLET_BALANCE= "GET_WALLET_BALANCE";
export const GET_WALLET_SETTING= "GET_WALLET_SETTING";
export const POST_EWT_BLOCK= "POST_EWT_BLOCK";
export const POST_MEM_ADDR_LIST= "POST_MEM_ADDR_LIST";
