export const POST_BAC_TABLE_LIST= "POST_BAC_TABLE_LIST";
export const POST_ALL_BAC_TABLE= "POST_ALL_BAC_TABLE";
export const POST_BAC_TRANS= "POST_BAC_TRANS";
export const POST_BAC_TRANS_DET= "POST_BAC_TRANS_DET";
export const POST_BAC_PAY_RATE= "POST_BAC_PAY_RATE";
export const POST_GET_TABLE= "POST_GET_TABLE";
export const POST_EDIT_BAC_TABLE= "POST_EDIT_BAC_TABLE";
