export const POST_NOTILIST= "POST_NOTILIST";
export const POST_MODULELIST= "POST_MODULELIST";
export const POST_NOTISEND= "POST_NOTISEND";
export const POST_NOTI_SEND= "POST_NOTI_SEND";
export const POST_GET_LANGUAGE_LIST= "POST_GET_LANGUAGE_LIST";
export const POST_MODULE_LIST= "POST_MODULE_LIST";

