export const GET_DASHBOARD_SALES = "GET_DASHBOARD_SALES";
export const GET_DASHBOARD_SICBO_SALES = "GET_DASHBOARD_SICBO_SALES";
export const GET_DASHBOARD_SLOT_SALES = "GET_DASHBOARD_SLOT_SALES";
export const GET_DASHBOARD_ROUL_SALES = "GET_DASHBOARD_ROUL_SALES";
