export const POST_TABLE_LISTING= "POST_TABLE_LISTING";
export const POST_WHEEL_SETTING= "POST_WHEEL_SETTING";
export const POST_EDIT_WHEEL= "POST_EDIT_WHEEL";
export const POST_ROUL_BET_TRANS= "POST_ROUL_BET_TRANS";
export const POST_ALL_ROUL_WHEEL= "POST_ALL_ROUL_WHEEL";
export const POST_ROUL_BET_TRANS_DET= "POST_ROUL_BET_TRANS_DET";
export const POST_ROUL_PAY_RATE= "POST_ROUL_PAY_RATE";
