export const GET_USER_MENU_LIST= "GET_USER_MENU_LIST";
export const POST_GROUP_MENU= "POST_GROUP_MENU";
export const GET_MENU_DETAIL= "GET_MENU_DETAIL";
export const POST_SIDEBAR_MENU= "POST_SIDEBAR_MENU";
